#!/usr/bin/env python3
inport time as t 
import skilstak.colors as c

def stuff():
    print("""
    pt = pythagorean theorem, 
    c = area of a circle
    s = area of a square, 
    sp = square pyramid surface area
    tr = area of a triangle
    pc = perimeter of a circle,
    y = equation solver, 
    t = area of a trapezoid
    ss = system solver, 
    st for triangular prism surface area
    sc for cube's surface area, 
    cu = volume of a cube,
    rs = rectangle surface area, 
    sps = surface area of sphere
    cs = cylinder surface area,
    sh = volume of a sphere,
    co = surface area of a cone
    oc = surface area of a octohedron
    tp = triangular prism surface area
    hp = hexagonal prism surface area
    rp = rectangular pyramid surface area
    hs = hemisphere surface area 
    sr = square root a number""")
if __name__ == '__main__':
    print(c.clear + c.multi("Welcome to the Ultimate Calculator") + c.x)
    import solver as s
    stuff()
    inpt = input(">> ")
    try:
        if inpt == "st":
            """surface area tri prism"""
            print(c.cl)
            s.satriprism()
        elif inpt == "oc":
            print(c.cl)
            s.octahedron()
        elif inpt == "hs":
            print(c.cl)
            s.hemisphere()
        elif inpt == "rs":
            """surface area rect prism"""
            print(c.cl)
            s.rectsurface()
        elif inpt == "co":
            print(c.cl)
            s.conesurface()
        elif inpt == "tp":
            print(c.cl)
            s.tripyramid()
        elif inpt == "rp":
            """surface area rect pyramid"""
            print(c.cl)
            s.rectpyramid()
        elif inpt == "sps":
            """surface area sphere"""
            print(c.cl)
            s.spheresurface()
        elif inpt == "sp":
            """surface area square pyramid"""
            print(c.cl)
            s.squarepyramid()
        elif inpt == "pc":
            """circum. of a circle"""
            print(c.cl)
            s.solve_perc()
        elif inpt == "sc":
            """surface area cube"""
            print(c.cl)
            s.sacube()
        elif inpt == "c":
            """area of a circle"""
            print(c.clear)
            s.solve_circle()
        elif inpt == "s":
            """area of a square"""
            print(c.clear)
            s.solve_square()
        elif inpt == "tr":
            """area of a triangle"""
            print(c.clear)
            s.solve_triangle()
        elif inpt == "t":
            """area of a trapezoid"""
            print(c.clear)
            s.solve_trapazoid()
        elif inpt == "y":
            print(c.clear)
            """Equation solver"""
            s.solve_system()
        elif inpt == "pt":
            """solves A^2 + B^2 = C^2"""
            print(c.clear)
            s.solve_py()
        elif inpt == "ss":
            """solves a system"""
            print(c.clear)
            s.solve_system2()
        elif inpt == "cu":
            """finds volume of a cube"""
            print(c.cl)
            s.solve_cube()
        elif inpt == "sh":
            """find volume of a sphere"""
            print(c.cl)
            s.solvesphere()
        elif inpt == "sr":
            """square root a number"""
            print(c.cl)
            s.solve_squareroot()
        elif inpt == "cs":
            """surface area cylinder"""
            print(c.cl)
            s.cylindersurface()
        elif inpt == "hp":
            print(c.cl)
            s.hexagon()
        else:
            print("Please use c, s, tr, or t, y, pt, or ss to choose which shape/formula to find the area of/solve.")
    except KeyboardInterrupt:
        exit()
