#!/usr/bin/env python3
import time as t
import skilstak.colors as c

if __name__ == '__main__':
    print(c.clear + c.multi("Welcome to the Ultimate Calculator") + c.x)
    print("pt = pythagorean theorem, c = area of a circle, s= area of a square, tr = area of a triangle")
    print("pc = perimeter of a circle, y = equation solver, t = area of a trapezoid, ss = system solver")
    print("cu = volume of a cube, sph = volume of a sphere, sr = square root a number")
    inpt = input(">> ")
    import solver as a
    try:
        if inpt == "pc":
            print(c.clear)
            a.solve_perc()
        elif inpt == "c":
            print(c.clear)
            a.solve_circle()
        elif inpt == "s":
            print(c.clear)
            a.solve_square()
        elif inpt == "tr":
            print(c.clear)
            a.solve_triangle()
        elif inpt == "t":
            print(c.clear)
            a.solve_trapazoid()
        elif inpt == "-":
            print(c.clear)
            """Equation solver"""
            a.solve_system()
        elif inpt == "pt":
            print(c.clear)
            a.solve_py()
        elif inpt == "ss":
            print(c.clear)
            a.solve_system2()
        elif inpt == "cu":
            print(c.cl)
            a.solve_cube()
        elif inpt == "sph":
            print(c.cl)
            a.solve_sphere
        elif inpt == "sr":
            print(c.cl)
            a.solve_squareroot()
        elif inpt == "si":
            print(c.cl)
            a.solve_inequality()
        else:
            print("Please use c, s, tr, or t, y, pt, or ss to choose which shape/formula to find the area of/solve.")
    except KeyboardInterrupt:
        exit()
