#!/usr/bin/env python3
import skilstak.colors as c
if __name__ == '__main__':
    try:
        print("Test")
        inpu = input("?")
        x = input("^?")
        y = int(x)
        z = int(inpu)
        w = int
        w = z ** y
        print(w)
    except KeyboardInterrupt:
        exit()
else:
    print("jiimmy")
