#!/usr/bin/env python3
import math
if __name__ == '__main__':
    try:
        i = int(input("what # to test? > "))
        squared_i = math.sqrt(i)
        ri = math.ceil(squared_i)
        if i < 3:
            print("too small")
            exit()
        elif i <= 16:
            ri = i
        is_prime = True
        for j in range(2,ri):
            if i%j == 0: #Says if there is a remainder
                is_prime = False
        if is_prime == True:
            print("Is prime")
        else:
            print("Not prime")
    except KeyboardInterrupt():
        exit()
