#!/usr/bin/env python3

bases = input("Please input your list of DNA bases here, with each codon separated by a space: ")
codons = bases.split(" ")
codons = [word.replace('g','f') for word in codons]  
codons = [word.replace('c','g') for word in codons]  
codons = [word.replace('a','u') for word in codons]  
codons = [word.replace('f','c') for word in codons]  
codons = [word.replace('t','a') for word in codons]  
print(codons)
for i, item in enumerate(codons):
    if codons[i] in ['uuu','uuc']:
        codons[i] = "Phe"
    elif codons[i] in ['uua','uug','cuu','cuc','cua','cug']:
        codons[i] = "Leu"
    elif codons[i] in ['auu','auc','aua']:
        codons[i] = "Ile"
    elif codons[i] == 'aug':
        codons[i] = "start"
    elif codons[i] in ['guc','guu','gua','gug']:
        codons[i] = "Val"
    elif codons[i] in ['ucu','ucc','uca','ucg']:
        codons[i] = "Ser"
    elif codons[i] in ['ccu','ccc','cca','ccg']:
        codons[i] = "Pro"
    elif codons[i] in ['acu','acc','aca','acg']:
        codons[i] = "Thr"
    elif codons[i] in ['gcu','gcc','gca','gcg']:
        codons[i] = "Ala"
    elif codons[i] in ['ugu','ugc']:
        codons[i] = "Tyr"
    elif codons[i] in ['uua','uag','uga']:
        codons[i] = "STOP"
    elif codons[i] in ['cau','cac']:
        codons[i] = "His"
    elif codons[i] in ['caa','cag']:
        codons[i] = "Gln"
    elif codons[i] in ['aau','aac']:
        codons[i] = "Asn"
    elif codons[i] in ['aaa','aag']:
        codons[i] = "Lys"
    elif codons[i] in ['gau','gac']:
        codons[i] = "Asp"
    elif codons[i] in ['gaa','gag']:
        codons[i] = "Glu"
    elif codons[i] in ['ugu','ugc']:
        codons[i] = "Cys"
    elif codons[i] in ['cgu','cgc','cga','cgg','aga','agg']:
        codons[i] = "Arg"
    elif codons[i] == "ugg":
        codons[i] = "Trp"
    elif codons[i] in ['agu','agc']:
        codons[i] = "Ser"
    elif codons[i] in ['ggu','ggc','gga','ggg']:
        codons[i] = "Gly"
    else:
        exit()
print(codons)
