#!/usr/bin/env python3
import math as m
import skilstak.colors as s
import time
def solve_quadratic():
    print("Welcome to Alexander's quadratic solver! This program will give you the solutions to a quadratic equation.")
    print("ax^2 + bx + c")
    a1 = input("What does a equal? ")
    b1 = input(s.clear + "What does b equal? ")
    c1 = input(s.clear + "What does c equal? ")
    a = float(a1)
    b = float(b1)
    c = float(c1)
    d = (b**2 - 4*a*c)
    if d < 0:
        print(str(a) + "x^2 + " + str(b) + "x + " + str(c))
        print("This quadratic has no solutions.")
    elif d >= 0:
        print(str(a) + "x^2 + " + str(b) + "x + " + str(c))
        desc = (m.sqrt(d))
        top1 = (-1*b + desc)
        top2 = (-1*b - desc)
        quad1 = (top1/2*a)
        quad2 = (top2/2*a)
        if quad1 == quad2:
            print("You have one solution:")
            print("{" + s.red + str(quad1) + s.x + "}")
        else:
            print("You have 2 solutions:")
            print("{" + s.red + str(quad1) + s.x + "," + s.red + str(quad2) + s.x + "}")

if __name__ == "__main__":
    solve_quadratic()

