#!/usr/bin/env python3
import math as m
import skilstak.colors as c
import time
def solve_quadratic():
    print("Welcome to Alexander's quadratic solver! This program will give you the solutions to a quadratic equation.")
    print("ax^2 + bx + c")
    a = input("What does a equal?")
    b = input(c.clear + "What does b equal?")
    c = input("What does c equal?")
    a = float()
    b = float()
    c = float()
    d = (b**2 - 4*a*c)
    if d < 0:
        print(str(a) + "x^2 + " + str(b) + "x + " + str(c))
        print("This quadratic has no solutions.")
    elif d => 0:
        print(str(a) + "x^2 + " + str(b) + "x + " + str(c))
        desc = (m.sqrt(d))
        top1 = (-1*b + desc)
        top2 = (-1b - desc)
        quad1 = (top1/2*a)
        quad2 = (top2/2*a)
        if quad1 == quad2:
            print("You have one solution:")
            print("{" + c.red + quad1 + c.x + "}")
        else:
            print("You have 2 solutions:")
            print("{" + c.red + quad1 + c.x + "," + c.red + quad2 + c.x + "}")

if __name__ == 

