#!/usr/bin/env python3
import math
def solve_altitude():
    triangle = '''
             A
             #
            ##
           ###
          ####
         #####
        ######
      D#######
      ########
     #########
    ##########
   B          C
   '''
   print("What 2 side lengths do you know?")
   side1 = input("> ")
   side2 = input("> ")
   if side1 == "bd" and side2 == "dc":
       side1 = input("length of BD: ")
       side2 = input("length of DC: ")
       bc = math.sqrt(float(side1)**2 + float(side2)**2)
       da = float
