#!/usr/bin/env python3
import math
import time

def solve_vertex():
  a = input("a: ")
  b = input("b: ")
  c = input("c: ")
  a = float()
  b = float()
  c = float()
  x = (-b)/(2.*a)
  y = -1 * (b**2.)/(4. * a)
  y = y + c
  print(c.clear + "vetex form is " + a + "(x - " + x + ") + " + y)

if __name__ == "__main__":
  solve_vertex()
